### PR TITLE
Feature/maintenance bob example embedded

### PR DESCRIPTION
**Pull request by sbixl**
The changes included, serve to maintain the [bob_examples_embedded](https://github.com/BobBuildTool/bob-example-containers) project. 

I hope it is not a problem that the Linux kernel has been upgraded to a 6.x version.  When building the kernel with version 5.x a compilation error occurs, which is (if i understood it correct) related to the GCC version provided by the basement layer. After upgrade to 6.x., it looks like all the patches for the kernel are no longer needed, but I'm not sure if they have another background.

### CODE REVIEW

**Comment by jkloetzke** [comment]
Thanks for the effort! If the Linux patches appear to be needed again, we can resurrect them from the history...
